language: node_js
node_js:
  - "6.1"
  - "5.7"
script: jasmine-node ./tests/backend
install: true
before_script:
  - npm install -g jasmine-node
  - npm install express
  - npm install underscore
  - npm install body-parser
  - npm install jasmine-jquery
